version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - './frontend:/app'
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://backend:5000 # Change this to match your backend API URL
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - './backend:/app'
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URL="mongodb+srv://rohanrustagi21:2uze6GF299kNrnBg@cluster0.hfi4hxs.mongodb.net/" # Change this to match your MongoDB connection URL
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - 'mongo_data:/data/db'

volumes:
  mongo_data:
